name: Build PsyDoom Latest Develop

on:
  workflow_dispatch: # Allows manual trigger

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true" # Forces Node 24 to fix the runner deprecation warning

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Original Develop Branch
        uses: actions/checkout@v4
        with:
          repository: 'BodbDearg/PsyDoom'
          ref: 'develop'

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build Binary
        run: |
          cmake --build build --config Release

      - name: Check Build Directories
        run: |
          echo "=== ROOT CONTROLS ==="
          Get-ChildItem -Directory
          echo "=== LOOKING FOR INTERMEDIATE EXE FILES ==="
          Get-ChildItem -Path . -Filter "PsyDoom*" -Recurse -ErrorAction SilentlyContinue | Select-Object FullName
        shell: pwsh

      - name: Upload Latest Develop Executable
        uses: actions/upload-artifact@v4
        with:
          name: PsyDoom-Windows-Binary
          path: |
            **/PsyDoom.exe
            **/Release/PsyDoom.exe
            **/build/Release/PsyDoom.exe
            **/exe/Release/PsyDoom.exe
            build/Release/
            exe/Release/
          if-no-files-found: warn
